'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux';
import ProviderSession from '@/components/Providers/Providers'
import { PersistGate } from 'redux-persist/integration/react'
import { store, Persistor } from '@/redux/store/store'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode,
  session: any
}) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <ProviderSession>
      <Provider store={store}>
      <PersistGate persistor={Persistor}>
        {children}
        </PersistGate>
        </Provider>
      </ProviderSession>
      </body>
    </html>
    
  )
}
