
import React, {Component} from 'react';
import './globals.css'
import ProviderSession from '@/components/Providers/Providers'
import Layout2 from '@/components/layout2';
import { Dancing_Script, Inter } from 'next/font/google';

const dancing = Dancing_Script({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dancing'})

const inter = Inter({ 
    subsets: ['latin'],
    display: 'swap',
    weight: ['400', '700'],
    variable: '--font-inter'})
  

export const metadata = {
      title: 'Create Next App',
      description: 'Generated by create next app',
    }

export default function RootLayout({
  children
}: {
  children: React.ReactNode,
  session: any
}) {
  return (
    
    <html lang="en" className={` ${inter.variable} ${dancing.variable} h-screen` }>
      <body className='h-screen' >
        <ProviderSession>
          <Layout2 children={children}/>
      </ProviderSession>
      <footer> <p className='text-center text-black'>CopyRights @ Virginia Mo</p></footer>
      </body>
    </html>
    
  )
}
